spring:
  application:
    name: verfuegbarkeits-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: verfuegbarkeit-service-${instance}

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true


