spring:
  application:
    name: verfuegbarkeits-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: verfuegbarkeit-service-${instance}

server:
  port: 0

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

opentracing:
  jaeger:
    service-name: verfuegbarkeits-service
    enabled: true
    udp-sender:
      host: localhost

